rooms = [
    "R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10", "R11", "R12",
    "H1", "H2", "H3",
    "C1", "C2", "C3", "C4",
    "B1", "B2", "B3",
    "P1", "P2", "P3",
    "E1", "E2", "E3", "E4",
    "L1", "L2", "L3", "L4", "L5", "L6",
    "M1", "M2", "M3", "M4", "M5", "M6",
    "G1", "G2",
    "Music School",
    "Gym", "Fitness Suite"
]

subjects = ["History", "Chemistry", "Biology", "Physics", "Computer Science", "French", "German", "Spanish", "Mathematics", "Geography", "Music", "English", "Economics", "Philosophy", "PE"]

subject_room = {
    "History": ["H1", "H2", "H3"],
    "Chemistry": ["C1", "C2", "C3", "C4"],
    "Biology": ["B1", "B2", "B3"],
    "Physics": ["P1", "P2", "P3"],
    "Computer Science": ["E1", "E2", "E3", "E4"],
    "French": ["L1", "L2", "L3", "L4", "L5", "L6"],
    "German": ["L1", "L2", "L3", "L4", "L5", "L6"],
    "Spanish": ["L1", "L2", "L3", "L4", "L5", "L6"],
    "Mathematics": ["M1", "M2", "M3", "M4", "M5", "M6"],
    "Geography": ["G1", "G2"],
    "Music": ["Music School"],
    "English": ["R1", "R2", "R3", "R4", "R5", "R6"],
    "Economics": ["R7", "R8", "R9"],
    "Philosophy": ["R12"],
    "PE": ["Gym", "Fitness Suite"]
}

y12_subject_classes = {
    "Mathematics": ["12A Mathematics", "12B Mathematics", "12C Mathematics"],
    "Physics": ["12B1 Physics", "12B2 Physics", "12C Physics", "12D Physics"],
    "Chemistry": ["12B1 Chemistry", "12B2 Chemistry", "12C1 Chemistry", "12C2 Chemistry"],
    "Biology": ["12C Biology", "12D Biology"],
    "History": ["12C History"],
    "Economics": ["12B Economics", "12C Economics", "12D Economics"],
    "Computer Science": ["12B Computer Science", "12C Computer Science", "12D Computer Science"],
    "French": ["12D French"],
    "German": ["12B German"],
    "Spanish": ["12D Spanish"],
    "Geography": ["12B Geography"],
    "Music": ["12B Music"],
    "English": ["12B English"],
    "Philosophy": ["12C Philosophy", "12D Philosophy"],
    "PE": ["12D PE"]
}

y12_class_lessons = {
    "12A Mathematics": 6,
    "12B Mathematics": 9,
    "12C Mathematics": 12,
    "12B1 Physics": 6,
    "12B2 Physics": 6,
    "12C Physics": 6,
    "12D Physics": 6,
    "12B1 Chemistry": 6,
    "12B2 Chemistry": 6,
    "12C1 Chemistry": 6,
    "12C2 Chemistry": 6,
    "12C Biology": 6,
    "12D Biology": 6,
    "12C History": 6,
    "12B Economics": 6,
    "12C Economics": 6,
    "12D Economics": 6,
    "12B Computer Science": 6,
    "12C Computer Science": 6,
    "12D Computer Science": 6,
    "12D French": 6,
    "12B German": 6,
    "12D Spanish": 6,
    "12B Geography": 6,
    "12B Music": 6,
    "12B English": 6,
    "12C Philosophy": 6,
    "12D Philosophy": 6,
    "12D PE": 6
}

y13_subject_classes = {
    "Mathematics": ["13A Mathematics", "13B Mathematics", "13C Mathematics"],
    "Physics": ["13B1 Physics", "13B2 Physics", "13C Physics", "13D Physics"],
    "Chemistry": ["13B1 Chemistry", "13B2 Chemistry", "13C1 Chemistry", "13C2 Chemistry"],
    "Biology": ["13C Biology", "13D Biology"],
    "History": ["13C History"],
    "Economics": ["13B Economics", "13C Economics", "13D Economics"],
    "Computer Science": ["13B Computer Science", "13C Computer Science", "13D Computer Science"],
    "French": ["13D French"],
    "German": ["13B German"],
    "Spanish": ["13D Spanish"],
    "Geography": ["13B Geography"],
    "Music": ["13B Music"],
    "English": ["13B English"],
    "Philosophy": ["13C Philosophy", "13D Philosophy"],
    "PE": ["13D PE"]
}

y13_class_lessons = {
    "13A Mathematics": 6,
    "13B Mathematics": 9,
    "13C Mathematics": 12,
    "13B1 Physics": 6,
    "13B2 Physics": 6,
    "13C Physics": 6,
    "13D Physics": 6,
    "13B1 Chemistry": 6,
    "13B2 Chemistry": 6,
    "13C1 Chemistry": 6,
    "13C2 Chemistry": 6,
    "13C Biology": 6,
    "13D Biology": 6,
    "13C History": 6,
    "13B Economics": 6,
    "13C Economics": 6,
    "13D Economics": 6,
    "13B Computer Science": 6,
    "13C Computer Science": 6,
    "13D Computer Science": 6,
    "13D French": 6,
    "13B German": 6,
    "13D Spanish": 6,
    "13B Geography": 6,
    "13B Music": 6,
    "13B English": 6,
    "13C Philosophy": 6,
    "13D Philosophy": 6,
    "13D PE": 6
}

y11_subject_classes = {
    "Mathematics": ["11A1 Mathematics", "11A2 Mathematics", "11A3 Mathematics",
                    "11B1 Mathematics", "11B2 Mathematics", "11B3 Mathematics"],
    "Physics": ["11A Physics", "11B Physics", "11C Physics", "11D Physics",
                "11E Physics", "11F Physics"],
    "Chemistry": ["11A Chemistry", "11B Chemistry", "11C Chemistry", "11D Chemistry",
                  "11E Chemistry", "11F Chemistry"],
    "Biology": ["11A Biology", "11B Biology", "11C Biology", "11D Biology",
                "11E Biology", "11F Biology"],
    "History": ["11A History", "11B History", "11C History", "11D History"],
    "Economics": ["11A Economics", "11B Economics", "11C Economics", "11D Economics"],
    "Computer Science": ["11A Computer Science", "11B Computer Science",
                         "11C Computer Science", "11D Computer Science"],
    "French": ["11A French", "11B French", "11C French", "11D French"],
    "German": ["11A German", "11B German", "11C German", "11D German"],
    "Spanish": ["11A Spanish", "11B Spanish", "11C Spanish", "11D Spanish"],
    "Geography": ["11A Geography", "11B Geography", "11C Geography", "11D Geography",
                  "11E Geography", "11F Geography"],
    "Music": ["11C Music"],
    "English": ["11AX English", "11AY English", "11AZ English",
                "11BX English", "11BY English", "11BZ English"],
    "Philosophy": ["11AX Philosophy", "11AY Philosophy", "11AZ Philosophy",
                   "11BX Philosophy", "11BY Philosophy", "11BZ Philosophy"],
    "PE": ["11A PE", "11B PE", "11C PE", "11D PE", "11E PE", "11F PE"]
}

y11_class_lessons = {
    "11A1 Mathematics": 6, "11A2 Mathematics": 6, "11A3 Mathematics": 6,
    "11B1 Mathematics": 6, "11B2 Mathematics": 6, "11B3 Mathematics": 6,
    "11A Physics": 6, "11B Physics": 6, "11C Physics": 6, "11D Physics": 6,
    "11E Physics": 6, "11F Physics": 6,
    "11A Chemistry": 6, "11B Chemistry": 6, "11C Chemistry": 6, "11D Chemistry": 6,
    "11E Chemistry": 6, "11F Chemistry": 6,
    "11A Biology": 6, "11B Biology": 6, "11C Biology": 6, "11D Biology": 6,
    "11E Biology": 6, "11F Biology": 6,
    "11A History": 6, "11B History": 6, "11C History": 6, "11D History": 6,
    "11A Economics": 6, "11B Economics": 6, "11C Economics": 6, "11D Economics": 6,
    "11A Computer Science": 6, "11B Computer Science": 6,
    "11C Computer Science": 6, "11D Computer Science": 6,
    "11A French": 6, "11B French": 6, "11C French": 6, "11D French": 6,
    "11A German": 6, "11B German": 6, "11C German": 6, "11D German": 6,
    "11A Spanish": 6, "11B Spanish": 6, "11C Spanish": 6, "11D Spanish": 6,
    "11A Geography": 6, "11B Geography": 6, "11C Geography": 6,
    "11D Geography": 6, "11E Geography": 6, "11F Geography": 6,
    "11C Music": 6,
    "11AX English": 6, "11AY English": 6, "11AZ English": 6,
    "11BX English": 6, "11BY English": 6, "11BZ English": 6,
    "11AX Philosophy": 6, "11AY Philosophy": 6, "11AZ Philosophy": 6,
    "11BX Philosophy": 6, "11BY Philosophy": 6, "11BZ Philosophy": 6,
    "11A PE": 6, "11B PE": 6, "11C PE": 6, "11D PE": 6, "11E PE": 6, "11F PE": 6
}

y10_subject_classes = {
    "Mathematics": ["10A1 Mathematics", "10A2 Mathematics", "10A3 Mathematics",
                    "10B1 Mathematics", "10B2 Mathematics", "10B3 Mathematics"],
    "Physics": ["10A Physics", "10B Physics", "10C Physics", "10D Physics",
                "10E Physics", "10F Physics"],
    "Chemistry": ["10A Chemistry", "10B Chemistry", "10C Chemistry", "10D Chemistry",
                  "10E Chemistry", "10F Chemistry"],
    "Biology": ["10A Biology", "10B Biology", "10C Biology", "10D Biology",
                "10E Biology", "10F Biology"],
    "History": ["10A History", "10B History", "10C History", "10D History"],
    "Economics": ["10A Economics", "10B Economics", "10C Economics", "10D Economics"],
    "Computer Science": ["10A Computer Science", "10B Computer Science",
                         "10C Computer Science", "10D Computer Science"],
    "French": ["10A French", "10B French", "10C French", "10D French"],
    "German": ["10A German", "10B German", "10C German", "10D German"],
    "Spanish": ["10A Spanish", "10B Spanish", "10C Spanish", "10D Spanish"],
    "Geography": ["10A Geography", "10B Geography", "10C Geography", "10D Geography",
                  "10E Geography", "10F Geography"],
    "Music": ["10C Music"],
    "English": ["10AX English", "10AY English", "10AZ English",
                "10BX English", "10BY English", "10BZ English"],
    "Philosophy": ["10AX Philosophy", "10AY Philosophy", "10AZ Philosophy",
                   "10BX Philosophy", "10BY Philosophy", "10BZ Philosophy"],
    "PE": ["10A PE", "10B PE", "10C PE", "10D PE", "10E PE", "10F PE"]
}

y10_class_lessons = {
    "10A1 Mathematics": 6, "10A2 Mathematics": 6, "10A3 Mathematics": 6,
    "10B1 Mathematics": 6, "10B2 Mathematics": 6, "10B3 Mathematics": 6,
    "10A Physics": 6, "10B Physics": 6, "10C Physics": 6, "10D Physics": 6,
    "10E Physics": 6, "10F Physics": 6,
    "10A Chemistry": 6, "10B Chemistry": 6, "10C Chemistry": 6, "10D Chemistry": 6,
    "10E Chemistry": 6, "10F Chemistry": 6,
    "10A Biology": 6, "10B Biology": 6, "10C Biology": 6, "10D Biology": 6,
    "10E Biology": 6, "10F Biology": 6,
    "10A History": 6, "10B History": 6, "10C History": 6, "10D History": 6,
    "10A Economics": 6, "10B Economics": 6, "10C Economics": 6, "10D Economics": 6,
    "10A Computer Science": 6, "10B Computer Science": 6,
    "10C Computer Science": 6, "10D Computer Science": 6,
    "10A French": 6, "10B French": 6, "10C French": 6, "10D French": 6,
    "10A German": 6, "10B German": 6, "10C German": 6, "10D German": 6,
    "10A Spanish": 6, "10B Spanish": 6, "10C Spanish": 6, "10D Spanish": 6,
    "10A Geography": 6, "10B Geography": 6, "10C Geography": 6,
    "10D Geography": 6, "10E Geography": 6, "10F Geography": 6,
    "10C Music": 6,
    "10AX English": 6, "10AY English": 6, "10AZ English": 6,
    "10BX English": 6, "10BY English": 6, "10BZ English": 6,
    "10AX Philosophy": 6, "10AY Philosophy": 6, "10AZ Philosophy": 6,
    "10BX Philosophy": 6, "10BY Philosophy": 6, "10BZ Philosophy": 6,
    "10A PE": 6, "10B PE": 6, "10C PE": 6, "10D PE": 6, "10E PE": 6, "10F PE": 6
}

y9_subject_classes = {
    "Mathematics": ["9A1 Mathematics", "9A2 Mathematics", "9A3 Mathematics",
                    "9B1 Mathematics", "9B2 Mathematics", "9B3 Mathematics"],
    "Physics": ["9A Physics", "9B Physics", "9C Physics", "9D Physics",
                "9E Physics", "9F Physics"],
    "Chemistry": ["9A Chemistry", "9B Chemistry", "9C Chemistry", "9D Chemistry",
                  "9E Chemistry", "9F Chemistry"],
    "Biology": ["9A Biology", "9B Biology", "9C Biology", "9D Biology",
                "9E Biology", "9F Biology"],
    "History": ["9A History", "9B History", "9C History", "9D History"],
    "Economics": ["9A Economics", "9B Economics", "9C Economics", "9D Economics"],
    "Computer Science": ["9A Computer Science", "9B Computer Science",
                         "9C Computer Science", "9D Computer Science"],
    "French": ["9A French", "9B French", "9C French", "9D French"],
    "German": ["9A German", "9B German", "9C German", "9D German"],
    "Spanish": ["9A Spanish", "9B Spanish", "9C Spanish", "9D Spanish"],
    "Geography": ["9A Geography", "9B Geography", "9C Geography", "9D Geography",
                  "9E Geography", "9F Geography"],
    "Music": ["9C Music"],
    "English": ["9AX English", "9AY English", "9AZ English",
                "9BX English", "9BY English", "9BZ English"],
    "Philosophy": ["9AX Philosophy", "9AY Philosophy", "9AZ Philosophy",
                   "9BX Philosophy", "9BY Philosophy", "9BZ Philosophy"],
    "PE": ["9A PE", "9B PE", "9C PE", "9D PE", "9E PE", "9F PE"]
}

y9_class_lessons = {
    "9A1 Mathematics": 6, "9A2 Mathematics": 6, "9A3 Mathematics": 6,
    "9B1 Mathematics": 6, "9B2 Mathematics": 6, "9B3 Mathematics": 6,
    "9A Physics": 6, "9B Physics": 6, "9C Physics": 6, "9D Physics": 6,
    "9E Physics": 6, "9F Physics": 6,
    "9A Chemistry": 6, "9B Chemistry": 6, "9C Chemistry": 6, "9D Chemistry": 6,
    "9E Chemistry": 6, "9F Chemistry": 6,
    "9A Biology": 6, "9B Biology": 6, "9C Biology": 6, "9D Biology": 6,
    "9E Biology": 6, "9F Biology": 6,
    "9A History": 6, "9B History": 6, "9C History": 6, "9D History": 6,
    "9A Economics": 6, "9B Economics": 6, "9C Economics": 6, "9D Economics": 6,
    "9A Computer Science": 6, "9B Computer Science": 6,
    "9C Computer Science": 6, "9D Computer Science": 6,
    "9A French": 6, "9B French": 6, "9C French": 6, "9D French": 6,
    "9A German": 6, "9B German": 6, "9C German": 6, "9D German": 6,
    "9A Spanish": 6, "9B Spanish": 6, "9C Spanish": 6, "9D Spanish": 6,
    "9A Geography": 6, "9B Geography": 6, "9C Geography": 6,
    "9D Geography": 6, "9E Geography": 6, "9F Geography": 6,
    "9C Music": 6,
    "9AX English": 6, "9AY English": 6, "9AZ English": 6,
    "9BX English": 6, "9BY English": 6, "9BZ English": 6,
    "9AX Philosophy": 6, "9AY Philosophy": 6, "9AZ Philosophy": 6,
    "9BX Philosophy": 6, "9BY Philosophy": 6, "9BZ Philosophy": 6,
    "9A PE": 6, "9B PE": 6, "9C PE": 6, "9D PE": 6, "9E PE": 6, "9F PE": 6
}

y8_subject_classes = {
    "Mathematics": ["8E Mathematics", "8C Mathematics", "8L Mathematics", "8S Mathematics", "8W Mathematics"],
    "Physics": ["8E Physics", "8C Physics", "8L Physics", "8S Physics", "8W Physics"],
    "Chemistry": ["8E Chemistry", "8C Chemistry", "8L Chemistry", "8S Chemistry", "8W Chemistry"],
    "Biology": ["8E Biology", "8C Biology", "8L Biology", "8S Biology", "8W Biology"],
    "History": ["8E History", "8C History", "8L History", "8S History", "8W History"],
    "Computer Science": ["8E Computer Science", "8C Computer Science", "8L Computer Science", "8S Computer Science", "8W Computer Science"],
    "French": ["8E French", "8C French", "8L French", "8S French", "8W French"],
    "German": ["8E German", "8C German", "8L German", "8S German", "8W German"],
    "Spanish": ["8E Spanish", "8C Spanish", "8L Spanish", "8S Spanish", "8W Spanish"],
    "Geography": ["8E Geography", "8C Geography", "8L Geography", "8S Geography", "8W Geography"],
    "Music": ["8E Music", "8C Music", "8L Music", "8S Music", "8W Music"],
    "English": ["8E English", "8C English", "8L English", "8S English", "8W English"],
    "Philosophy": ["8E Philosophy", "8C Philosophy", "8L Philosophy", "8S Philosophy", "8W Philosophy"],
    "PE": ["8E PE", "8C PE", "8L PE", "8S PE", "8W PE"]
}

y8_class_lessons = {
    "8E Mathematics": 6, "8C Mathematics": 6, "8L Mathematics": 6, "8S Mathematics": 6, "8W Mathematics": 6,
    "8E Physics": 6, "8C Physics": 6, "8L Physics": 6, "8S Physics": 6, "8W Physics": 6,
    "8E Chemistry": 6, "8C Chemistry": 6, "8L Chemistry": 6, "8S Chemistry": 6, "8W Chemistry": 6,
    "8E Biology": 6, "8C Biology": 6, "8L Biology": 6, "8S Biology": 6, "8W Biology": 6,
    "8E History": 6, "8C History": 6, "8L History": 6, "8S History": 6, "8W History": 6,
    "8E Computer Science": 6, "8C Computer Science": 6, "8L Computer Science": 6, "8S Computer Science": 6, "8W Computer Science": 6,
    "8E French": 6, "8C French": 6, "8L French": 6, "8S French": 6, "8W French": 6,
    "8E German": 6, "8C German": 6, "8L German": 6, "8S German": 6, "8W German": 6,
    "8E Spanish": 6, "8C Spanish": 6, "8L Spanish": 6, "8S Spanish": 6, "8W Spanish": 6,
    "8E Geography": 6, "8C Geography": 6, "8L Geography": 6, "8S Geography": 6, "8W Geography": 6,
    "8E Music": 6, "8C Music": 6, "8L Music": 6, "8S Music": 6, "8W Music": 6,
    "8E English": 6, "8C English": 6, "8L English": 6, "8S English": 6, "8W English": 6,
    "8E Philosophy": 6, "8C Philosophy": 6, "8L Philosophy": 6, "8S Philosophy": 6, "8W Philosophy": 6,
    "8E PE": 6, "8C PE": 6, "8L PE": 6, "8S PE": 6, "8W PE": 6
}

y7_subject_classes = {
    "Mathematics": ["7E Mathematics", "7C Mathematics", "7L Mathematics", "7S Mathematics", "7W Mathematics"],
    "Physics": ["7E Physics", "7C Physics", "7L Physics", "7S Physics", "7W Physics"],
    "Chemistry": ["7E Chemistry", "7C Chemistry", "7L Chemistry", "7S Chemistry", "7W Chemistry"],
    "Biology": ["7E Biology", "7C Biology", "7L Biology", "7S Biology", "7W Biology"],
    "History": ["7E History", "7C History", "7L History", "7S History", "7W History"],
    "Computer Science": ["7E Computer Science", "7C Computer Science", "7L Computer Science", "7S Computer Science", "7W Computer Science"],
    "French": ["7E French", "7C French", "7L French", "7S French", "7W French"],
    "German": ["7E German", "7C German", "7L German", "7S German", "7W German"],
    "Spanish": ["7E Spanish", "7C Spanish", "7L Spanish", "7S Spanish", "7W Spanish"],
    "Geography": ["7E Geography", "7C Geography", "7L Geography", "7S Geography", "7W Geography"],
    "Music": ["7E Music", "7C Music", "7L Music", "7S Music", "7W Music"],
    "English": ["7E English", "7C English", "7L English", "7S English", "7W English"],
    "Philosophy": ["7E Philosophy", "7C Philosophy", "7L Philosophy", "7S Philosophy", "7W Philosophy"],
    "PE": ["7E PE", "7C PE", "7L PE", "7S PE", "7W PE"]
}

y7_class_lessons = {
    "7E Mathematics": 6, "7C Mathematics": 6, "7L Mathematics": 6, "7S Mathematics": 6, "7W Mathematics": 6,
    "7E Physics": 6, "7C Physics": 6, "7L Physics": 6, "7S Physics": 6, "7W Physics": 6,
    "7E Chemistry": 6, "7C Chemistry": 6, "7L Chemistry": 6, "7S Chemistry": 6, "7W Chemistry": 6,
    "7E Biology": 6, "7C Biology": 6, "7L Biology": 6, "7S Biology": 6, "7W Biology": 6,
    "7E History": 6, "7C History": 6, "7L History": 6, "7S History": 6, "7W History": 6,
    "7E Computer Science": 6, "7C Computer Science": 6, "7L Computer Science": 6, "7S Computer Science": 6, "7W Computer Science": 6,
    "7E French": 6, "7C French": 6, "7L French": 6, "7S French": 6, "7W French": 6,
    "7E German": 6, "7C German": 6, "7L German": 6, "7S German": 6, "7W German": 6,
    "7E Spanish": 6, "7C Spanish": 6, "7L Spanish": 6, "7S Spanish": 6, "7W Spanish": 6,
    "7E Geography": 6, "7C Geography": 6, "7L Geography": 6, "7S Geography": 6, "7W Geography": 6,
    "7E Music": 6, "7C Music": 6, "7L Music": 6, "7S Music": 6, "7W Music": 6,
    "7E English": 6, "7C English": 6, "7L English": 6, "7S English": 6, "7W English": 6,
    "7E Philosophy": 6, "7C Philosophy": 6, "7L Philosophy": 6, "7S Philosophy": 6, "7W Philosophy": 6,
    "7E PE": 6, "7C PE": 6, "7L PE": 6, "7S PE": 6, "7W PE": 6
}
